# Generated by Django 4.1 on 2023-02-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_answer_auth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="auth",
            new_name="author",
        ),
    ]
