# Generated by Django 4.1 on 2023-02-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0004_rename_auth_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
